# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pokemon App' do
  pod 'Kingfisher', '~> 7.0'
end

target 'Pokemon AppTests' do
  pod 'Kingfisher', '~> 7.0'
end
